version: '3.8'

services:

  simple_notes_service:

    container_name: simple_notes_container

    image: mysql:8.0

    restart: always

    environment:

      MYSQL_DATABASE: 'simple_notes_db'

      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: '1234'

    ports:
      - '3303:3306'